Repository mozilla/terraform-modules, pull requests merged in 2025-02, with the labels that each got.

#257 fix(docs): Sign commits for documentation changes
  .github/actions/action.yml
Labels: no-release

#255 chore(google_project) - added PAM API to default audit logging list in terraform
  google_project/locals.tf
Labels: patch

#258 fix(ci): Correct reference to GitHub token
  .github/actions/action.yml
Labels: patch

#259 feat(google_gke): added configuration for control_plane_endpoints_config, updated versions and added variable to toggle
  google_gke/README.md
  google_gke/cluster.tf
  google_gke/variables.tf
  google_gke/versions.tf
Labels: minor

#260 Adding additional permissions for FxA devs to be able to view job his…
  google_permissions/other_roles.tf
  google_permissions/outputs.tf
Labels: minor

#261 moving cloudtask roles to folder additional roles instead of project …
  google_permissions/outputs.tf
Labels: patch

#253 feat(google_gke_namespace_logging): Output linked dataset ID
  .github/actions/action.yml
  google_gke_namespace_logging/README.md
  google_gke_namespace_logging/outputs.tf
Labels: minor

#263 feat(google_gke): Output cluster id
  google_gke/README.md
  google_gke/outputs.tf
Labels: patch

#265 SRELEAD-301: Expose generated uptime checks in google_monitoring.
  google_monitoring/README.md
  google_monitoring/outputs.tf
Labels: minor

#266 chore(google_gke_namespace_logging): Add description for output
  google_gke_namespace_logging/README.md
  google_gke_namespace_logging/outputs.tf
Labels: patch
