Repository mozilla/terraform-modules, pull requests merged in 2025-03, with the labels that each got.

#267 fix(google_permissions) complete removal of var.entitlement_enabled from other_roles, add secret roles to default ent
  google_permissions/other_roles.tf
  google_permissions/pam_entitlement.tf
Labels: patch

#269 norelease: version:refname in tagging logic to avoid collisions
  .github/actions/action.yml
Labels: no-release

#270 chore:run pre-commit
  google_permissions/ADDING_NEW_ROLE.md
  google_permissions/Design.md
Labels: patch

#271 feat(Fastly Waf): Create Fastly WAF Module with GCP Logging
  google_fastly_waf/.terraform-docs.yaml
  google_fastly_waf/README.md
  google_fastly_waf/bigquery.tf
  google_fastly_waf/certificate.tf
  google_fastly_waf/examples/README.md
  google_fastly_waf/examples/example.tf
  google_fastly_waf/gcs.tf
  google_fastly_waf/iam.tf
  google_fastly_waf/logging/bq_format.txt
  google_fastly_waf/main.tf
  google_fastly_waf/outputs.tf
  google_fastly_waf/provider.tf
  google_fastly_waf/variables.tf
  google_fastly_waf/vcl/main.vcl.tftpl
  google_fastly_waf/versions.tf
Labels: major

#274 Fastly waf updates
  google_fastly_waf/provider.tf
  google_fastly_waf/variables.tf
Labels: minor

#273 postgres password validation policy
  google_cloudsql_postgres/README.md
  google_cloudsql_postgres/main.tf
  google_cloudsql_postgres/variables.tf
Labels: minor

#276 fix(google-permissions) fix loop bug in slack project_feed - OPST-1914
  google_permissions/pam_entitlement.tf
Labels: patch

#277 fix(fastly): Make subscription domain optional
  google_fastly_waf/certificate.tf
  google_fastly_waf/outputs.tf
Labels: major

#278 fix(google-permissions) create cloud asset service account for PAM slack - OPST-1914
  google_permissions/pam_entitlement.tf
Labels: patch

#264 chore(google_permissions) - added roles needed for @mozilla.com mops users - OPST-1891
  google_permissions/pam_entitlement.tf
Labels: patch

#279 chore(google_fastly_waf): Allow Terraform provider google v6
  google_fastly_waf/versions.tf
Labels: patch
