Repository mozilla/terraform-modules, pull requests merged in 2025-09, with the labels that each got.

#372 fix(ci): downgrade artifact download to 4.3.0
  .github/workflows/monorepo.yml
Labels: no-release

#370 feat(google_project): allow specifying default bucket log retention
  google_project/README.md
  google_project/main.tf
  google_project/variables.tf
Labels: minor

#378 fix(fastly): Add application/geo+json mime type to compression list
  google_fastly_waf/main.tf
Labels: patch

#386 fix(ci): fix gha paths
  .github/workflows/monorepo.yml
Labels: no-release
