Repository mozilla/terraform-modules, pull requests merged in 2025-07, with the labels that each got.

#319 Added CloudSQL to use in SVCSE-3162
  google_permissions/outputs.tf
Labels: minor

#321 feat(google_cloudsql_postgres): Add variables for Query Insights to match mysql module
  google_cloudsql_mysql/README.md
  google_cloudsql_mysql/examples/psc/main.tf
  google_cloudsql_mysql/main.tf
  google_cloudsql_mysql/variables.tf
  google_cloudsql_postgres/README.md
  google_cloudsql_postgres/examples/psc/main.tf
  google_cloudsql_postgres/main.tf
  google_cloudsql_postgres/variables.tf
Labels: minor

#322 Adding read endpoint and read endpoint port to outputs
  google_redis/README.md
  google_redis/outputs.tf
Labels: patch

#323 Adding read_replicas_mode and replica_count variables
  google_redis/README.md
  google_redis/main.tf
  google_redis/variables.tf
Labels: patch

#324 chore: Add simple PR template.
  .github/PULL_REQUEST_TEMPLATE.md
  .github/pull_request_template.md
Labels: no-release

#326 fix:rm changelog generation
  .github/actions/action.yml
  .github/workflows/monorepo.yml
Labels: no-release

#328 fix(google_redis): Defaults for replica_count and read_replicas_mode vary on tier
  google_redis/README.md
  google_redis/variables.tf
Labels: minor

#329 fix(fastly): Add a depends to the edge site definition
  google_fastly_waf/main.tf
Labels: minor
