Repository mozilla/terraform-modules, pull requests merged in 2025-04, with the labels that each got.

#281 OPST-2084 Add-in config setting for cluster autoscale behavior
  google_gke/README.md
  google_gke/cluster.tf
  google_gke/variables.tf
Labels: minor

#282 fix: Correctly interpolate the variable
  .github/actions/action.yml
Labels: patch

#283 chore(google_gke): White space change to trigger tagging of new release
  google_gke/k8s_api_proxy.tf
Labels: minor

#284 feat(certificate_map): Output DNS authorization records
  google_certificate_manager_certificate_map/README.md
  google_certificate_manager_certificate_map/outputs.tf
  google_certificate_manager_certificate_map/service.tf
Labels: minor

#285 feat(google_workload_identity): removed data source and updated outputs to use provided service account name and email
  google_workload_identity/README.md
  google_workload_identity/main.tf
  google_workload_identity/outputs.tf
  google_workload_identity/variables.tf
Labels: major

#288 fix(google_gke_tenant): pin gke_service_account module version
  google_gke_tenant/gke_service_account.tf
Labels: major

#287 Revert "feat(google_workload_identity): removed data source and updated outputs to use provided service account name and email"
  google_workload_identity/README.md
  google_workload_identity/main.tf
  google_workload_identity/outputs.tf
  google_workload_identity/variables.tf
Labels: major

#289 feat(google_monitoring): Add alert policies support for uptime checks.
  google_monitoring/README.md
  google_monitoring/alert_policy.tf
  google_monitoring/uptime_checks.tf
  google_monitoring/variables.tf
Labels: major

#290 chore(google_monitoring): Correct documentation errors.
  google_monitoring/README.md
Labels: documentation

#293 fix(zizmor): Update based on new zizmor rule
  .github/actions/action.yml
  .github/workflows/ci.yaml
  .github/workflows/monorepo.yml
Labels: no-release

#291 feat(google_cloudsql_mysql): add support for ENTERPRISE_PLUS on replicas
  google_cloudsql_mysql/README.md
  google_cloudsql_mysql/main.tf
  google_cloudsql_mysql/variables.tf
Labels: minor

#295 feat(google_cloudsql_mysql): enable data cache on replicas if enterprise plus
  google_cloudsql_mysql/README.md
  google_cloudsql_mysql/main.tf
  google_cloudsql_mysql/variables.tf
Labels: minor

#294 feat:add ability to override name suffix
  google_cdn-external/README.md
  google_cdn-external/main.tf
  google_cdn-external/variables.tf
Labels: minor

#296 feat(google_cloudsql_postgres): add support for ENTERPRISE_PLUS on replicas
  google_cloudsql_postgres/README.md
  google_cloudsql_postgres/main.tf
  google_cloudsql_postgres/variables.tf
Labels: minor

#292 fix(google_gke_namespace_logging): Prevent loss of logs when modifying log sink
  google_gke_namespace_logging/README.md
  google_gke_namespace_logging/main.tf
  google_gke_namespace_logging/outputs.tf
  google_gke_namespace_logging/variables.tf
Labels: major

#297 fix(google_gke_namespace_logging): Allow passing empty string as service account
  google_gke_namespace_logging/main.tf
Labels: patch

#300 fix:update substitution to strictly grab last 5 chars
  .github/actions/action.yml
Labels: no-release

#299 fix:give backend_bucket_name_override a default value
  .github/workflows/monorepo.yml
  google_cdn-external/README.md
  google_cdn-external/variables.tf
Labels: patch
